# Generated by Django 5.2.3 on 2025-07-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_interview_summary_interview_transcript_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
